In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd
df = pd.read_csv('Loan_DataSet.csv')

## **Operations on Loan DataSet**

View the First/Last Few Rows

In [4]:
df.head()

df.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

Value Counts for a Specific Column

In [5]:
# Count unique values in the 'Loan_Status' column
df['Loan_Status'].value_counts()

# Count unique values in the 'Gender' column
df['Gender'].value_counts()

Gender
Male      489
Female    112
Name: count, dtype: int64

Filtering Rows

In [6]:
# Filter rows where ApplicantIncome is greater than 5000
high_income = df[df['ApplicantIncome'] > 5000]
high_income.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N
20,LP001043,Male,Yes,0,Not Graduate,No,7660,0.0,104.0,360.0,0.0,Urban,N

Sorting Data

In [9]:
# Sort by LoanAmount in ascending order
df.sort_values(by='LoanAmount', inplace=True)

# Sort by LoanAmount in descending order
df.sort_values(by='LoanAmount', ascending=False, inplace=True)

print(df.sort_values)

<bound method DataFrame.sort_values of       Loan_ID  Gender Married Dependents     Education Self_Employed  \
171  LP001585     NaN     Yes         3+      Graduate            No
130  LP001469    Male      No          0      Graduate           Yes
155  LP001536    Male     Yes         3+      Graduate            No
561  LP002813  Female     Yes          1      Graduate           Yes
369  LP002191    Male     Yes          0      Graduate            No
..        ...     ...     ...        ...           ...           ...
479  LP002533    Male     Yes          2      Graduate            No
524  LP002697    Male      No          0      Graduate            No
550  LP002778    Male     Yes          2      Graduate           Yes
551  LP002784    Male     Yes          1  Not Graduate            No
605  LP002960    Male     Yes          0  Not Graduate            No

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
171            51763                0.0       700.0             300.0
130            20166                0.0       650.0             480.0
155            39999                0.0       600.0             180.0
561            19484                0.0       600.0             360.0
369            19730             5266.0       570.0             360.0
..               ...                ...         ...               ...
479             2947             1603.0         NaN             360.0
524             4680             2087.0         NaN             360.0
550             6633                0.0         NaN             360.0
551             2492             2375.0         NaN             360.0
605             2400             3800.0         NaN             180.0

     Credit_History Property_Area Loan_Status
171             1.0         Urban           Y
130             NaN         Urban           Y
155             0.0     Semiurban           Y
561             1.0     Semiurban           Y
369             1.0         Rural           N
..              ...           ...         ...
479             1.0         Urban           N
524             1.0     Semiurban           N
550             0.0         Rural           N
551             1.0         Rural           Y
605             1.0         Urban           N

[614 rows x 13 columns]>